blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [

      path('',views.home,name='home'),
      path('about/',views.about,name='about'),
      path('blog/<int:pk>/',views.detail,name='detail'),
      path('cv/',views.cv,name='cv'),
      path('login/',views.login_view,name='login'),
      path('logout/',views.logout_view,name='logout'),
      path('register/',views.register,name='register'),
      path('blog/<int:pk>/comment/', views.comment_form, name='comment_form'),
      path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
      path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
      path('post/new/', views.CreatePostView.as_view(), name='post_new'),
      path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
      path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),


]

blog_pro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateField()
    body = models.TextField()
    name = models.CharField(max_length=100,)



    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

    def get_absolute_url(self):
        return reverse("blog:detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title



class Comment(models.Model):
    blog = models.ForeignKey('blog.Blog',on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)


    def approve(self):
        self.approved_comment = True
        self.save()


    def get_absolute_url(self):
            return reverse("home")


    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Blog, Comment


class SignUpForm(UserCreationForm):

    email = forms.EmailField(max_length=254, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields =  ('author','text')

class PostForm(forms.ModelForm):


    class Meta():
        model = Blog
        fields = ('name','title','body','pub_date')


    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['body'].widget.attrs['class'] = 'form-control'
        self.fields['pub_date'].widget.attrs['class'] = 'form-control'


        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),

        }

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect,redirect
from .models import Blog , Comment
from django.contrib.auth import authenticate, login ,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm, CommentForm , PostForm
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.
def home(request):
    blogs = Blog.objects.all()
    return render(request,'blog/home.html',{'blogs':blogs})

def about(request):
    return render(request,'blog/about.html',{})

def detail(request, pk):
    dblog = get_object_or_404(Blog, pk=pk)
    return render(request,'blog/detail.html',{'dblog':dblog})

def cv(request):
    return render(request,'blog/cv.html',{})

def login_view(request):
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        messages.success(request, ('You Have Been Logged In!'))
        return redirect('blog:home')
    else:
         messages.success(request,('Error Logging In - Please Try Again..'))
         return redirect('login')
  return render(request, 'blog/login.html')

def logout_view(request):
     logout(request)
     messages.success(request, ('You Have Been Logged Out!'))
     return redirect('blog:about')

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request,('Congrats! You have registered.'))
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'blog/register.html', {'form': form})

@login_required
def comment_form(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.save()
            return redirect('blog:detail', pk=blog.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:detail', pk=comment.blog.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:detail', pk=comment.blog.pk)

class CreatePostView(LoginRequiredMixin,CreateView):
      login_url = '/login/'
      redirect_field_name = 'blog/detail.html'

      form_class = PostForm

      model = Blog
class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/detail.html'

    form_class = PostForm

    model = Blog


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:home')

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}

{% block body_block %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
<style class="text/css">


.JumboHeaderImg{
background-image: url("/static/images/fa.jpg");
background-size: cover;
}

.fon{
  font-family: 'Bree Serif', serif;
}
* {
  box-sizing: border-box;
}



/* Center website */
.main {
  max-width: 1000px;
  margin: auto;
}

h1 {
  font-size: 50px;
  word-break: break-all;
}

.row {
  margin: 8px -16px;
}

/* Add padding BETWEEN each column */
.row,
.row > .column {
  padding: 8px;
}

/* Create four equal columns that floats next to each other */
.column {
  float: left;
  width: 25%;
}

/* Clear floats after rows */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Content */
.content {
  background-color: white;
  padding: 10px;
}

/* Responsive layout - makes a two column-layout instead of four columns */
@media screen and (max-width: 900px) {
  .column {
    width: 50%;
  }
}

/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
  }
}
.jumbotron .container{
position: relative;
bottom: 0;
height: 20px;
}
#ju{
  background: black;
  margin-bottom: 0;
  width: 100%;


}

#f{
  font-family: 'Bree Serif', serif;
  color: white;
}

</style>


<div class="jumbotron JumboHeaderImg">
  <br>
  <br>
<h1><p style="color:white">WELCOME TO MY BLOG.</p></h1><hr>
    <div class="container">
      <div class="text-left" font="white"><br>
         <br>
          <br>




    </div>
  </div>
     <br>
     <br>
<br>
</div>

 <div class="fon">


  <h3>Hi,I am Bhavy Bhatia and i love to learn new things and try to do it practically.</h3>
  <p>This is my First Site related to the Blogs and i hope that you like it.</p>

</div>
<div class="main">

 <div class="row">
  <div class="column">
    <div class="content">
    <a href="https://www.instagram.com/p/BudnyzagVS6/"><img src="/static/images/bh3.PNG" alt="Mountains" style="width:100%"></a>
      <h3>My Work</h3>
      <p>Lorem ipsum dolor sit amet, tempor prodesset eos no. Temporibus necessitatibus sea ei, at tantas oporteat nam. Lorem ipsum dolor sit amet, tempor prodesset eos no.</p>
    </div>
  </div>
  <div class="column">
    <div class="content">
     <a href="https://www.instagram.com/p/B510QCxgjMY/"><img src="/static/images/bh2.PNG" alt="Lights" style="width:100%"></a>
      <h3>My Work</h3>
      <p>Lorem ipsum dolor sit amet, tempor prodesset eos no. Temporibus necessitatibus sea ei, at tantas oporteat nam. Lorem ipsum dolor sit amet, tempor prodesset eos no.</p>
    </div>
  </div>
  <div class="column">
    <div class="content">
     <a href="https://www.instagram.com/p/B6vTTKaAVdZ/"><img src="/static/images/bh.PNG" alt="Nature" style="width:100%"></a>
      <h3>My Work</h3>
      <p>Lorem ipsum dolor sit amet, tempor prodesset eos no. Temporibus necessitatibus sea ei, at tantas oporteat nam. Lorem ipsum dolor sit amet, tempor prodesset eos no.</p>
    </div>
  </div>
  <div class="column">
    <div class="content">
  <a href="https://www.instagram.com/p/BuMDr9CgO2v/"> <img src="/static/images/bh4.PNG" alt="Mountains" style="width:100%"></a>
      <h3>My Work</h3>
      <p>Lorem ipsum dolor sit amet, tempor prodesset eos no. Temporibus necessitatibus sea ei, at tantas oporteat nam. Lorem ipsum dolor sit amet, tempor prodesset eos no.</p>
    </div>
  </div>
</div>
<!-- END GRID -->
</div>

<div class="jumbotron" id="ju">
  <div class="container">

    <div class="text-center" style="text-align: center">


  <p class="text-center" id="f">Enter email address</p>
  <input type="email" id="f" name="email" value=""class="text-center" placeholder="Enter Email" style="width:300px;">
  </div>
  </div>
  <footer class="text-muted" align="bottom"><br><br><br>
    <div class="container text-center">
       <p>&copy;Bhavy Bhatia {% now "Y" %} Blog</p>
  </footer>


</div>



{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!doctype html>

<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


    <title>About Me</title>
  <style>
#alt{
     margin-top: 50px;
     background: white;
     border-color: white;
     font-size: 20px;
}


  </style>

  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="{% url 'blog:about' %}">About Me</a>
     <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> ☰
     </button>
     <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
           {%  if user.is_authenticated %}

             <li>
                 <a href="{% url 'blog:home' %}" class="nav-link">Blog</a>
             </li>
             <li>
                 <a href="{% url 'blog:cv' %}" class="nav-link">CV</a>
             </li>
            {% else %}
               <li></li>
            {% endif %}

         </ul>
         <ul class="nav navbar-nav ml-auto">
           {%  if user.is_authenticated %}
             <li>
               <a href="{% url 'blog:logout' %}" class="nav-link">Logout</a>
             </li>
           {% else %}
             <li>
               <a href="{% url 'blog:login' %}" class="nav-link">Login</a>
             </li>
             <li>
               <a href="{% url 'blog:register' %}" class="nav-link">Register</a>
             </li>
           {% endif %}
                 <a href="https://github.com/bhvbhatia" class="nav-link"><i class="fa fa-github fa-lg"></i></a>
             <li>
                 <a href="https://www.linkedin.com/in/bhavy-bhatia-175292150/" class="nav-link"><i class="fa fa-linkedin fa-lg"></i></a>
             <li>
                 <a href="https://www.instagram.com/bhavy_arvy12/" class="nav-link"><i class="fa fa-instagram fa-lg"></i></a>
             </li>
         </ul>
     </div>
     <!--/.nav-collapse -->

</nav>
    <div class="container">
      <br><br>
      {% if messages %}
         {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" id="alt" role="alert">
                                <p>{{ message }}</p>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
               </button>
            </div>
         {% endfor %}
      {% endif %}



    </div>

    {% block body_block %}

    {% endblock %}






    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/javascript.util/0.12.12/javascript.util.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>











  </body>
</html>

blog/templates/blog/blog_confirm_delete.html
extends "blog/base.html" %}
{% block content %}
 <form action="" method="post">{% csrf_token %}
   <p>Are you sure you want to delete "{{ object }}"?</p>
   <input class='btn btn-danger' type="submit" value="Confirm" />
 </form>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}

{% block body_block %}


<style>
.jumbotron{
  margin-left: 420px;
  margin-right: 420px;
  padding-bottom: 30px;
  padding-left: 30px;
  padding-right: 30px;
  background-color: white;
}
body{
  background-color:  #18a370;
}

</style>


<br><br>
<body>

</body>

<div class="jumbotron">

<div align="center">

    <h1>New post</h1>

    <form method="POST" class="post-form">
    {% csrf_token %}
    {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
   {% endfor %}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>
</div>
</div>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}


{% block body_block %}
<style>

.jumbotron{
  margin-left: 420px;
  margin-right: 420px;
  padding-bottom: 30px;
  padding-left: 30px;
  padding-right: 30px;
  background-color: white;
}

#frm{
  width:70%;
}
body{
  background-color: #18a370;
}
button{
  background: #18a370;
  border-radius: 4px;
}
</style>

<br><br><br>
<body>

</body>
<div class="jumbotron">


<div align="center">


    <h1>Leave your comment</h1><br>
  <form action="" method="POST" class="form-group">
     {% csrf_token %}
       {{form.as_p}}

    <button type="submit" class="save btn btn-default" style="color:white">Post Comment</button>
    </form>
</div>
</div>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

blog/templates/blog/cv.html
{% extends 'blog/base.html' %}

{% block body_block %}
<br><br><br><br><br>
<link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">

<style>
h1{
  font-family: 'Merriweather', serif;
  font-size: 65px;
}
span{
  background-color:
}
#ye{
  background-color: yellow;
  margin-left: 0;
  text-align: center;
  width: 50%;

}
.p h1{
  font-family: 'Merriweather', serif;
  font-size: 55px;
  margin-right: 50px;
}

.intro{
  margin-right: 50px;

}
#edu{
  background-color: yellow;
  margin-left: 0;
  text-align: center;
  width: 50%;

}

#in{
  background-color: yellow;
  margin-left: 0;
  text-align: center;
  width: 50%;

}
#inte{
  margin-right: 50px;

}
#un{
  margin-right: 50px;

}

</style>
<div class="container" id="ye">

  <h1><strong><span>CV</span></strong></h1><br>

</div>
<br>

<div class="p" style="text-align:right">
   <h1><strong>Professional</strong> Summary</h1><br><br>
 <div class="intro">


   <p>Hi I'm Bhavy Bhatia currently pursuing Btech in Computer Science and Engineering from</p>
   <p>JECRC UNIVERSITY.Hardworking and technically profecient engineer who thrives when facing</p>
   <p>challenges and tackling long problem.Working on improving programing analytical skills</p>
   <p><strong>Techinal skills include MYSQL,Python,django,Data Structures and Algorithm.</strong></p>
   <br>
   <p>I have done data science course from <strong>IBM ONLINE CERTIFICATION</strong> and receive a completion</p>
   <p>certificate from IBM. Currently I'm working on Machine learning and AI model of Bank.</p>
</div><br><br>
</div><br>

<div class="container" id="edu">
  <mark><h1>EDUCATION</h1></mark><br>
</div><br><br>
  <div class="container" style="text-align: right" id="un">
 <h3><strong>University Name</strong></h3>
    <p>JECRC UNIVERSITY</p>
  </div><br><br><br>

  <div class="container" id="in">
    <mark><h1>INTEREST</h1></mark><br>
  </div><br><br>
  <div class="container" style="text-align:right" id="inte">
    <p>hddhchhdbchdbchdbchdbchdbcdbchdbchdcb</p>
    <p>chbhcbbhchchdbchdbchhdbcjdbcjdjbcjdbc</p>
    <p>hcbdhcbhdbchdbchdcbhdvvydvdgdvcghdvch</p>
    <p>ddcgvdgcvdhucdhcvdhubcjdcbjdcbhdbchhh</p>
 </div>


{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block body_block %}
<br><br>
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Arial;
  font-size: 17px;
}

.container {
  position: relative;
  max-width: 1600px;
  margin: 0px;
}

.container img{
  position: fixed;
  margin-top: -60px;
  margin-left: -15px;
  margin-right: -1000px;
}

.container .content {
  position: absolute;
  top: 0;
  background: rgb(0, 0, 0); /* Fallback color */
  background: rgba(0, 0, 0, 0); /* Black background with 0.5 opacity */
  color: black;
  width: 70%;
  margin-left: 30px;
  font-size: 30px;
  margin-top: -30px;

}
#cmt{
  position: absolute;

  margin-top: 250px;
  margin-left: 50px;

}
.comment{
  position: absolute;
  margin-top: 300px;
  margin-left: 50px;
  margin-bottom: 30px;

}
#nocmt{
  position: fixed;
  margin-top: 350px;
  margin-left: 50px
}
.er{

}
</style>

<div class="container">
  <img src="/static/images/de.PNG" alt="Notebook" style="width:100%;">
   <div class="content">
     <p style="background:yellow"> <strong>Publish on:</strong> {{dblog.pub_date_pretty}}</p>
     <p style="background:yellow"><strong>Title: </strong>{{dblog.title}}</p>
     <p style="background:yellow"><strong>Description:</strong> {{dblog.body}}</p>
     <p style="background:yellow"><strong>Publish By:</strong> {{dblog.name|safe|linebreaksbr}}</p><br>
  <div class="er" align="center">


     {% if user.is_authenticated %}
         <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=dblog.pk %}"><span class="fa fa-pencil"></span></a>
         <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=dblog.pk %}"><span class="fa fa-window-close"></span></a>

     {% endif %}
     </div>
  </div>
  <hr>
<a class="btn btn-dark" id="cmt" style="color:white" href="{% url 'blog:comment_form' pk=dblog.pk %}">Add comment</a>
{% for comment in dblog.comments.all %}
<br>
   {% if user.is_authenticated or comment.approved_comment %}
   <div class="comment">
       <div class="date">
         {% if not comment.approved_comment %}
         <br><br><br>
               <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="fa fa-window-close"></span></a>
               <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="fa fa-check"></span></a>
        {% endif %}
      </div>

        <p><strong>{{ comment.created_date }}</strong></p>
        <p><strong>{{ comment.text|safe|linebreaks }}</strong></p>
        <strong>Posted By: {{ comment.author }}</strong>
       <br><br><br>
   </div>
  {% endif %}
{% empty %}
  <strong><p id='nocmt'>No comments here yet :(</p></strong>
{% endfor %}
</div>




{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block body_block %}
<style class='text/css'>
.JumboHeaderImg{
background-image: url("/static/images/lib.jpg");
background-size: cover;
}
#n{
  font-size: 30px;
  margin-bottom: 50px;
  padding-bottom: 30px;
}



</style>

<div class="jumbotron JumboHeaderImg">
  <div class="container"><br><br><br><br><br>
    <div class="text-center">
      <h1 style="color:white">Welcome To Blogs</h1>
    </div>
  <br><br>

  </div>
  </div>
    <div class="container">
        {% csrf_token %}

        {% if user.is_authenticated %}
                <h2 style="text-align:center;">Hello {{ user.username }}</h2>



            {% else %}
                <h2></h2>
            {% endif %}


  <h2 id="l">Latest Post</h2><div align="right">


     <strong><a id='n' href="{% url 'blog:post_new' %}">New Post</a></strong>
     </div>

  <hr>
  {% for blog in blogs %}
  <div class="t">



      <a href="{% url 'blog:detail' pk=blog.pk %}"><h3>{{ blog.title }}</h3></a>
      <p>Publish On: {{blog.pub_date_pretty}}</p>
      <a href="{% url 'blog:detail' pk=blog.pk %}">Comments: {{ blog.approve_comments.count }}</a>

</div>
         <br>
  {% endfor %}

  <div class="container">


  </div>
  <footer class="text-muted" align="bottom"><br><br><br>
    <div class="container text-center">
       <p>&copy;Bhavy Bhatia {% now "Y" %} Blog</p>
  </footer>

{% endblock %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block body_block %}
<style>
.jumbotron{
  margin-left: 470px;
  margin-right: 470px;
  padding-top: -200px;
  background-color: white;

}
.form-control{
  width: 60%;
}
body{
  background-color: #18a370;
}
button{
  background: #18a370;
  border-radius: 4px;

  padding-left: 25px;
  padding-right: 25px;
  padding-top: 5px;
}


</style>

<body>

</body>
           <br><br><br>
  <div class="jumbotron " style="">


      <div align="center">
        <h1>Login</h1><hr>

          <form action="" method="post">
                     {% csrf_token %}

                     <div class="form-group">
                      <label for="username">username</label>
                      <input type="text" class="form-control" placeholder="Username" name="username">
                    </div>

                   <div class="form-group">
                     <label for="password">Password:</label>
                     <input type="password" class="form-control" name="password" placeholder="password">
                    </div>

            <button type="submit" class="btn btn-default" style="color:white"><h5>Login</h5></button><hr>
              <small>Don't have an account! <a href="{% url 'blog:register' %}">Sign up here</a> </small>
       </form>
     </div>

 </div>

{% endblock %}

blog/templates/blog/register.html
{% extends "blog/base.html" %}

{% block body_block %}
  <br><br><br><br>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<style>
  .jumbotron{
    position: fixed;
    margin-top: -65px;
    margin-left: 500px;
    margin-right: 300px;
    background: white;
    margin-bottom: 3000px;
    padding-top: 20px;
    padding-bottom: 30px;
    padding-left: 80px;
    padding-right: 80px;
  }
small{
text-align: left;
padding-left: -100px;
  }
  body{
    background-color: #18a370;
  }
  button{
    background: #18a370;
    border-radius: 4px;
    padding: 5px;
    padding-left: 15px;
    padding-right: 15px;
    padding-top: 5px;
  }


  </style>

<body>

</body>

<div class="jumbotron">

<div align="center">
 <h2 style=""><strong>Sign up</strong></h2>
 <small style="color:grey">Please fill this form to create an account</small><hr>
 <form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
   {% endfor %}

        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>




   </p><br>
    <button type="submit" style="color: white;"><h5>Sign up</h5></button>
  </form>
</div>
</div>
</div>
{% endblock %}